= Using multiple databases with Spring Data MongoDB

image:https://travis-ci.org/labcabrera/sample-spring-mongo-cross-domain.svg?branch=master["Build Status", link="https://travis-ci.org/labcabrera/sample-spring-mongo-cross-domain"]

:sample-ddd-extension: https://github.com/labcabrera/sample-spring-mongo-ddd-extension

== Introducción

El objetivo de este ejemplo es mostrar las capacidades que nos ofrece https://spring.io/projects/spring-data-mongodb[Spring Data MongoDB]
a la hora de trabajar con *diferentes bases de datos*.

En esta guía se analizan las diferentes modalidades de acceso a MongoDB:

* Utilizando `MongoTemplate`.
* Utilizando `MongoRepository`.
* Utilizando el objeto `Predicate` de http://www.querydsl.com/[QueryDSL].
* Convirtiendo RSQL a un `Predicate` de QueryDSL a través de la librería https://github.com/vineey/archelix-rsql[com.github.vineey:rsql-querydsl-all].
* Convirtiendo RSQL a un `Criteria` de Spring Mongo a través de la librería https://github.com/RutledgePaulV/rest-query-engine[com.github.rutledgepaulv:rest-query-engine].

== Resultados

Como veremos posteriormente, la librería QueryDSL tiene limitaciones al utilizar modelos distribuídos.
Los resultados utilizando la librería _rest-query-engine_ han sido los esperados.

== Modelo

[options="header",cols="1,1,2,3"]
|===
|Entidad       |Nombre        |Database              |Descripcion
|Productos     |`Product`     |_mongo-sample-shared_ |Representa un producto que tiene asociados
                                                      diferentes acuerdos marco.
|Acuerdo marco |`Agreement`   |_mongo-sample-shared_ |Cada uno de los acuerdos marcos asociados a un
                                                      producto.
|País          |`Country`     |_mongo_sample-shared_ |País.
|Persona       |`Person`      |_mongo-sample-app_    |Representa una persona relacionada con un
                                                      contrato.
|Contrato      |`Contract`    |_mongo-sample-app_    |Representa un contrato asociado a un producto.
                                                      El contrato tendrá un único tomador (holder) y
                                                      una lista de beneficiarios (recipients).
|===

En este modelo vemos que tanto los productos como acuerdos *están definidos en una base de datos
diferente* a la que utilizamos por nuestra API:

[source]
----
> db.adminCommand({listDatabases:1, nameOnly:true})
{
        "databases" : [
                {
                        "name" : "admin"
                },
                {
                        "name" : "config"
                },
                {
                        "name" : "local"
                },
                {
                        "name" : "mongo-sample-app"
                },
                {
                        "name" : "mongo-sample-shared"
                }
        ],
        "ok" : 1
}
----

Mongo permite establecer referencias a bases de datos externas utilizando
https://docs.mongodb.com/manual/reference/database-references/#dbrefs[DBRefs].

Esto está implementado por la anotación de Spring:

[source,java]
----
  @DBRef(db = "mongo-sample-shared")
  private Agreement agreement;
----

Al realizar la consulta desde la consola de mongo vemos que el objeto DBRef tiene asociado el nombre
de la base de datos que contiene el documento asociado:

----
> db.contracts.find('5c014aec27b0492c989168a0')
{ "_id" : ObjectId("5c014aec27b0492c989168a0"),
"contractNumber" : "100000000001",
"agreement" : DBRef("agreements", "10001", "mongo-sample-shared"),
"holder" : DBRef("persons", ObjectId("5c0143a327b0493fd4a190ba")),
"recipients" : [ DBRef("persons", ObjectId("5c0143a327b0493fd4a190ba")) ],
"_class" : "org.lab.samples.mongo.api.model.Contract" }
>
----

Spring es capaz de resolver el documento externo. Esto podemos verlo funcionando a través del siguiente ejemplo:

[source,java]
----
    @Test
    public void findUsingQuery() {
        Query query = new Query(Criteria.where("agreement.id").is("10001"));
        List<Contract> results = mongoOperations.find(query, Contract.class);
        System.out.println("Contract search by agreement using Query results:");
        results.forEach(e -> System.out.println(e));
        Assert.assertFalse(results.isEmpty());
    }
----

[source]
----
Contract search by agreement using Query results:
Contract(id=5c0265c2faea554cb78ec924, contractNumber=100000000001, agreement=Agreement(id=10001, name=Agreement 10001, product=null), ... 
Contract(id=5c0265c2faea554cb78ec925, contractNumber=100000000002, agreement=Agreement(id=10001, name=Agreement 10001, product=null), ...
Contract(id=5c0265c2faea554cb78ec926, contractNumber=100000000003, agreement=Agreement(id=10001, name=Agreement 10001, product=null), ...
Contract(id=5c0265c2faea554cb78ec927, contractNumber=100000000004, agreement=Agreement(id=10001, name=Agreement 10001, product=null), ...
Contract(id=5c0265c2faea554cb78ec928, contractNumber=100000000005, agreement=Agreement(id=10001, name=Agreement 10001, product=null), ...
----

Vemos que resuelve correctamente el acuerdo y sus propiedades aunque no es capaz de obtener el
producto, aunque podríamos obtenerlo haciendo una consulta al acuerdo marco a través de un
`MongoTemplate` que apunte a la base de datos compartida.


== Estructura del ejemplo

En nuestro ejemplo tenemos tres proyectos:

* *sample-shared-model*: definición del modelo que sería compartido por diferentes aplicaciones.
* *sample-api-model*: definición del modelo específico de nuestra aplicación.
* *sample-api*: API de ejemplo que utilizaremos para probar las expresiones de consulta a nuestro
  modelo utilizando RSQL.

== Utilizando QueryDSL

[NOTE]
====
Tanto en _master_ como en _develop_ no está incluido QueryDSL. Los ejemplos están en el branch
_querydsl_ del repositorio.
====

QueryDSL es una buena librería de cara a tener un modelo agnóstico, nos permite abstraernos del
modelo de persistencia y podríamos tener funcionando las mismas entidades utilizando Mongo o JPA.

Spring nos provee de la interface `QuerydslPredicateExecutor` que nos permite operar con el objeto
`Predicate` de QueryDSL.

De cara a la exposición de los servicios también tenemos la librería _rsql-querydsl-all_ que nos
permite convertir una expresión de búsqueda RSQL a un objeto `Predicate`.

Hasta aquí todo bien, pero en la práctica la conversión de RSQL a Predicate cuando trabajamos con
_DBRefs_ tiene limitaciones.

Un ejemplo sencillo es el siguiente:

[source,java]
----
  public void findUsingPredicate() {
    Predicate predicate = QContract.contract.agreement.id.eq("10001");
    Page<Contract> page = repository.findAll(predicate, PageRequest.of(0, 10));
    System.out.println("Contract search by agreement using Predicate results:");
    page.getContent().forEach(e -> System.out.println(e));
  }
----

El predicate que obtenemos es _contract.agreement.id = 10001_ que posteriormente se resuelve como:

----
find using query: { "agreement" : { "$ref" : "agreements" , "$id" : "10001"} }
----

Vemos que aunque detecta la relación, no detecta que el dbref hace referencia a una base de datos
diferente. La consulta correcta es:

----
find using query: { "agreement" : { "$ref" : "agreements" , "$id" : "10001" , "$db" : "mongo-sample-shared"} }
----

Por esta razón *no podremos utilizar QueryDSL* para realizar consultas a un modelo de Mongo
compuesto por diferentes esquemas.


[NOTE]
====
Aunque el que no funcione parece condición necesaria para no utilizar QueryDSL, también esto nos
ahorra un problema con el plugin de gradle a la hora de establecer las dependencias del proyecto.
El plugin _com.ewerk.gradle.plugins.querydsl_ (al menos en su versión 1.0.10) requiere que todas las
dependencias estén a nivel _compile_, incluídas también las que sólo deberían utilizarse para laç
compilación como por ejemplo _lombok_. Preescindiendo del plugin evitamos tener que declarar estas
dependencias incorrectamente, algo que luego requeriría no propagarlas de forma transitiva a todos
los proyectos que utilizasen nuestro modelo.
====

== Uilizando REST Query Engine

Dado que no podemos utilizar QueryDSL otra alternativa que tenemos para seguir utilizando RSQL para
la exposición de nuestra API es la librería _rest-query-engine_.

Esta trabaja a través de la API de Spring, utilizando el objeto _org.springframework.data.mongodb.core.query.Criteria_
del siguiente modo:

[source,java]
----
  @Test
  public void findUsingRSQL() {
    QueryConversionPipeline pipeline = QueryConversionPipeline.defaultPipeline();
    String rsql = "agreement.id==10001";
    Condition<GeneralQueryBuilder> condition = pipeline.apply(rsql, Contract.class);
    Criteria query = condition.query(new MongoVisitor());
    List<Contract> results = mongoOperations.find(new Query(query), Contract.class);
    Assert.assertFalse(results.isEmpty());
    System.out.println("Contract search by agreement using RSQL results:");
    results.forEach(e -> System.out.println(e));
  }
----

Si ejecutamos este test veremos que la query que se ejecuta es la correcta y este fragmento de
código produce la siguiente salida:

----
Contract search by agreement using RSQL results:
Contract(id=5c0265c2faea554cb78ec924, contractNumber=100000000001, agreement=Agreement(id=10001, name=Agreement 10001, product=null), ...
Contract(id=5c0265c2faea554cb78ec925, contractNumber=100000000002, agreement=Agreement(id=10001, name=Agreement 10001, product=null), ...
Contract(id=5c0265c2faea554cb78ec926, contractNumber=100000000003, agreement=Agreement(id=10001, name=Agreement 10001, product=null), ...
Contract(id=5c0265c2faea554cb78ec927, contractNumber=100000000004, agreement=Agreement(id=10001, name=Agreement 10001, product=null), ...
Contract(id=5c0265c2faea554cb78ec928, contractNumber=100000000005, agreement=Agreement(id=10001, name=Agreement 10001, product=null), ...
----

Utilizando el objeto _Query_ perdemos la capacidad de emplear _MongoRepository_, y por lo tanto
también la de trabajar directamente con _PagingAndSortingRepository_. Por esta razón nuestra capa de
servicios estaría acoplada a MongoDB y ya no podríamos por ejemplo utilizar JPA (posibilidad que nos
ofrece el uso de _repositories_ al ser independientes de la implementación).

Al no obtener directamente los objetos `Optional` y `Page` que nos proporcionan los _repositories_
de Spring, deberemos definir un servicio que genere estos objetos a partir de nuestro `MongoTemplate`:

[source,java]
----
public abstract class RsqlSearchService<E> {

  private final Class<E> entityClass;

  @Autowired
  private MongoTemplate mongoTemplate;

  protected RsqlSearchService(Class<E> entityClass) {
    this.entityClass = entityClass;
  }

  public Optional<E> findById(String id) {
    return Optional.ofNullable(mongoTemplate.findById(id, entityClass));
  }

  public Page<E> findAll(Pageable pageable) {
    return findAll(null, pageable);
  }

  public Page<E> findAll(String search, Pageable pageable) {
    Query query;
    if (StringUtils.isNotBlank(search)) {
      QueryConversionPipeline pipeline = QueryConversionPipeline.defaultPipeline();
      Condition<GeneralQueryBuilder> condition = pipeline.apply(search, entityClass);
      Criteria criteria = condition.query(new MongoVisitor());
      query = new Query(criteria);
    }
    else {
      query = new Query();
    }
    long count = mongoTemplate.count(query, entityClass);
    query.with(pageable);
    List<E> results = mongoTemplate.find(query, entityClass);
    return new PageImpl<E>(results, pageable, count);
  }
}
----

=== Extendiendo tipos no soportados (LocalDate y LocalDateTime)

La librería por defecto no soporta las conversiones a _LocalDate_ o _LocalDateTime_. Para ello
debemos implementar los conversores de Spring. Tenemos por ejemplo:

[source,java]
----
public class StringToLocalDateConverter implements Converter<String, LocalDate> {

  @Override
  public LocalDate convert(String source) {
    return LocalDate.parse(source);
  }
}
----

Después registraremos esta clase en un `StringToTypeConverter` de la librería y generarenos el
objeto `QueryConversionPipeline` del modo siguiente:

[source,java]
----
  QueryConversionPipeline pipeline = QueryConversionPipeline.builder()
    .useNonDefaultArgumentConversionPipe(DefaultArgumentConversionPipe.builder()
    .useNonDefaultStringToTypeConverter(new CustomSpringConversionServiceConverter()).build())
    .build();
----

Una vez realizado ya podremos hacer búsquedas como la siguiente:

[source,java]
----
  @Test
  public void testSearchBefore() {
    get("/persons?search=birthDate=lt=1980-01-01")
    .then()
    .assertThat().statusCode(200).and()
    .assertThat().body("_embedded", Matchers.notNullValue())
    .assertThat().body("page.size", Matchers.is(10))
    .assertThat().body("page.totalElements", Matchers.is(2));
  }
----

== API de búsqueda utilizando atributos de un DBRef diferentes al identificador

Dado que MongoDB no permite hacer joins al estilo de JPA, si queremos por ejemplo buscar las polizas
asociadas a un cliente a partir de su número de documento de identidad en lugar del _id_ deberemos
primero resolver el cliente para después componer la consulta.

Por ejemplo, a la hora de hacer búsquedas por un cliente en los contratos podríamos tener un servicio
similar al siguiente:

[source,java]
----
  public Page<Contract> findByCustomerIdCard(String search, String idCardNumber, Pageable pageable) {
    Query query = new Query();

    if (StringUtils.isNotBlank(search)) {
      Condition<GeneralQueryBuilder> condition = pipeline.apply(search, entityClass);
      Criteria criteria = condition.query(new MongoVisitor());
      query.addCriteria(criteria);
    }

    if (StringUtils.isNotEmpty(idCardNumber)) {
      Optional<Person> optionalPerson = personService.findByIdCardNumber(idCardNumber);
      if (optionalPerson.isPresent()) {
        String personId = optionalPerson.get().getId();
        Criteria criteria = new Criteria().orOperator(
          Criteria.where("holder.id").is(personId),
          Criteria.where("recipients").is(new DBRef("persons", new ObjectId(personId))));
        query.addCriteria(criteria);
      }
    }

    long count = mongoTemplate.count(query, entityClass);
    query.with(pageable);
    List<Contract> results = mongoTemplate.find(query, entityClass);
    return new PageImpl<Contract>(results, pageable, count);
  }
----

Vemos que en el caso de detectar que el _idCardNumber_ viene informado obtenemos el id de la persona y
posteriormente hacemos un _or_ de la búsqueda por el campo _holder_ (many-to-one) y _recipients_ (one-to-many).

== Definiendo varios MongoTemplate utilizando Spring Boot

Para poder trabajar con varios `MongoTemplate` en primer lugar deberemos deshabilitar la
auto-configuración:

[source,yml]
----
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
----

Después simplemente crearemos dos beans del modo siguiente:

[source,java]
----
  @ConfigurationProperties(prefix = "mongodb")
  public class ApiMongoProperties {

    private MongoProperties app = new MongoProperties();
    private MongoProperties shared = new MongoProperties();

  }

  @Configuration
  @EnableConfigurationProperties(ApiMongoProperties.class)
  public class MongoConfig {

    @Autowired
	  private ApiMongoProperties mongoProperties;

    @Primary
    @Bean(name = "appMongoTemplate")
    public MongoTemplate primaryMongoTemplate() throws Exception {
      return new MongoTemplate(primaryFactory(this.mongoProperties.getApp()));
    }

    @Bean(name = "sharedMongoTemplate")
    public MongoTemplate secondaryMongoTemplate() throws Exception {
      return new MongoTemplate(secondaryFactory(this.mongoProperties.getShared()));
    }
}
----

Finalmente podremos inyectar en nuestros servicios el template que necesitemos:

[source,java]
----
  @Autowired
  private MongoTemplate mongoTemplate;

  @Autowired
  @Qualifier("sharedMongoTemplate")
  private MongoTemplate sharedMongoTemplate;
----

== Ejecutando el ejemplo

En primer lugar necesitaremos una base de datos de mongo. La opción más cómoda es hacerlo vía docker:

----
docker run --name sample-mongo -p 27017:27017 -d mongo:4
----

A continuación ejecutaremos la aplicación. A través de http://localhost:8080 accederemos al panel de
Swagger donde podremos realizar las diferentes consultas. 
